[build]
  command = "npm run build:h5"
  publish = "dist/build/h5"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "16"
  VUE_APP_API_BASE_URL = "https://face-api-9xer.onrender.com"
